
# check-setup ensures all prerequisites are satisfied.
# This target is run before every other target and will block its execution if anything is amiss
.PHONY: check-setup
check-setup:
ifndef AWS_REGION
	$(error AWS_REGION is undefined)
endif
	@echo All required env variables are defined

ifeq (, $(shell which aws))
	$(error "aws cli is required to execute this project")
endif
