Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  IgwAssociation:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VpcId
  IgwRoute:
    Type: AWS::EC2::Route
    Properties: 
      GatewayId: !Ref InternetGateway
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: rtb-19ebf17d
